name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Corre todos los días a medianoche (UTC)
  workflow_dispatch:      # Permite correrlo manualmente
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repo
        uses: actions/checkout@v3

      - name: Generar snake
        uses: Platane/snk@v3
        with:
          github_user_name: leaby3ne
          outputs: dist/snake.svg

      - name: Subir snake al branch output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
